package:
  name: ros-noetic-geometry2
  version: 0.7.5
source:
  git_url: https://github.com/ros-gbp/geometry2-release.git
  git_rev: release/noetic/geometry2/0.7.5-1
  folder: ros-noetic-geometry2/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 8
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - ros-noetic-tf2
    - ros-noetic-tf2-bullet
    - ros-noetic-tf2-eigen
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-kdl
    - ros-noetic-tf2-msgs
    - ros-noetic-tf2-py
    - ros-noetic-tf2-ros
    - ros-noetic-tf2-sensor-msgs
    - ros-noetic-tf2-tools
  run:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-tf2
    - ros-noetic-tf2-bullet
    - ros-noetic-tf2-eigen
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-kdl
    - ros-noetic-tf2-msgs
    - ros-noetic-tf2-py
    - ros-noetic-tf2-ros
    - ros-noetic-tf2-sensor-msgs
    - ros-noetic-tf2-tools
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
