package:
  name: ros-noetic-hector-trajectory-server
  version: 0.5.2
source:
  git_url: https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release.git
  git_rev: release/noetic/hector_trajectory_server/0.5.2-4
  folder: ros-noetic-hector-trajectory-server/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 8
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - ros-noetic-hector-map-tools
    - ros-noetic-hector-nav-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf
  run:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-hector-map-tools
    - ros-noetic-hector-nav-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
